import type { StreamDiagnostics } from "../platforms/gfn/webrtcClient";

export function defaultDiagnostics(): StreamDiagnostics {
  return {
    connectionState: "closed",
    inputReady: false,
    connectedGamepads: 0,
    resolution: "",
    codec: "",
    hardwareAcceleration: "",
    colorCodec: "",
    isHdr: false,
    bitrateKbps: 0,
    targetBitrateKbps: 0,
    decodeFps: 0,
    renderFps: 0,
    packetsLost: 0,
    packetsReceived: 0,
    packetLossPercent: 0,
    jitterMs: 0,
    rttMs: 0,
    framesReceived: 0,
    framesDecoded: 0,
    framesDropped: 0,
    decodeTimeMs: 0,
    renderTimeMs: 0,
    jitterBufferDelayMs: 0,
    inputQueueBufferedBytes: 0,
    inputQueuePeakBufferedBytes: 0,
    partiallyReliableInputQueueBufferedBytes: 0,
    partiallyReliableInputQueuePeakBufferedBytes: 0,
    inputQueueDropCount: 0,
    inputQueueMaxSchedulingDelayMs: 0,
    partiallyReliableInputOpen: false,
    mouseMoveTransport: "reliable",
    mouseFlushIntervalMs: 8,
    mousePacketsPerSecond: 0,
    mouseResidualMagnitude: 0,
    mouseAdaptiveFlushActive: false,
    mouseBatchAgeMs: 0,
    frameAgeMs: 0,
    framePacingVarianceMs: 0,
    lagReason: "unknown",
    lagReasonDetail: "Waiting for stream stats",
    gpuType: "",
    serverRegion: "",
    decoderPressureActive: false,
    decoderRecoveryAttempts: 0,
    decoderRecoveryAction: "none",
    bitrateCeilingKbps: 0,
    bitrateEwmaKbps: 0,
    bitrateCeilingHeadroomPercent: 0,
    frameDropClass: "unknown",
    frameDropClassDetail: "Waiting for frame samples",
    mousePressureGuardActive: false,
    mousePressureGuardReason: "none",
    mousePressureGuardSamples: 0,
    cursorCalibrationScaleX: 1,
    cursorCalibrationScaleY: 1,
    cursorCalibrationRoundingPx: 0,
    routeMeasurementLabel: "single",
    routeMeasurementSamples: 0,
    routeMeasurementConfidence: "low",
    audioOutputMode: "direct",
    audioContextState: "none",
    audioContextBaseLatencyMs: 0,
    audioContextOutputLatencyMs: 0,
    audioSampleRate: 0,
    audioCurrentTime: 0,
    videoCurrentTime: 0,
    videoAudioOffsetMs: 0,
    micState: "uninitialized",
    micEnabled: false,
  };
}
